#
# Managed Subscribe Module Settings
#

# The IP address and port number that the base service listens on for the gRPC requests.
# Example: "0.0.0.0:80"
base_authority: <<value>>

# Information for how to get the Managed Subscribe URI. Only one source can be uncommented at a time.
managed_subscribe_uri_source:

  # The Managed Subscribe URI will be retrieved from this settings file.
  # 'service_uri' - The URI that the Managed Subscribe service listens on for requests.
  Local:
    service_uri: <<value>>

  # The Managed Subscribe URI will be discovered through Chariott.
  # 'chariott_uri' - The URI that the Chariott service listens on for requests.
  # 'service_identifier' - The service identifier for the Managed Subscribe service.
  # Chariott:
  #   chariott_uri: <<value>>
  #   service_identifier:
  #     namespace: <<value>>
  #     name: <<value>>
  #     version: <<value>>
