#
# Streaming Consumer Settings
#

# The URI that the in-vehicle digital twin service listens on for digital twin requests.
invehicle_digital_twin_uri: <<value>>

# The URI that the Chariott service listens on for requests.
# If you wish to use Chariott, then uncomment this setting and comment out the invehicle_digital_twin_uri setting.
# chariott_uri: <<value>>

# The number of images that we wish to stream.
number_of_images: <<value>>

