#
# Streaming Provider Settings
#

# The IP address and port number that the provider listens on for provider requests.
# Example: "0.0.0.0:80"
provider_authority: <<value>>

# The URL that the in-vehicle digital twin service listens on for digital twin requests.
invehicle_digital_twin_url: <<value>>

# The URL that the Chariott service listens on for requests.
# If you wish to use Chariott, then uncomment this setting and comment out the invehicle_digital_twin_url setting.
# chariott_url: <<value>>

# The directory where the images can be found.
image_directory: <<value>>
